name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Run tests
      run: |
        echo "Test de suma:"
        python -m unittest test_suma.py
        echo "Test de resta:"
        python -m unittest test_resta.py
        echo "Test de multiplicación:"
        python -m unittest test_multiplicacion.py
        echo "Test de división:"
        python -m unittest test_division.py
